version: "3"

services:
  mininet:
    image: opennetworking/mn-stratum:latest
    privileged: true
    ports:
      - "50001:50001"
      - "50002:50002"
      - "50003:50003"
      - "50004:50004"
    volumes:
      - ./tmp:/tmp
      - ./topo:/topo
    entrypoint: "/topo/entrypoint.sh"
  onos:
    image: onosproject/onos:2.2.0
    depends_on:
      - mininet
    ports:
      - "8181:8181" # GUI
      - "8101:8101" # CLI
    environment:
      - ONOS_APPS=gui,drivers.bmv2,lldpprovider,hostprovider,proxyarp,route-service
    links:
      - mininet
